/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Players */
        get: operations["players_api_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_v1_scenarios_get"];
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_api_v1_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_v1_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setpieces/montecarlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Montecarlo */
        post: operations["montecarlo_api_v1_setpieces_montecarlo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setpieces/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Routines */
        get: operations["list_routines_api_v1_setpieces_routines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setpieces/schemes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Schemes */
        get: operations["list_schemes_api_v1_setpieces_schemes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setpieces/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_v1_setpieces_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sim-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Sim Run */
        post: operations["create_sim_run_api_v1_sim_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sim-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sim Run */
        get: operations["get_sim_run_api_v1_sim_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sim-runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sim Run Events */
        get: operations["sim_run_events_api_v1_sim_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_v1_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EventDTO */
        EventDTO: {
            /** Kind */
            kind: string;
            /** Player Id */
            player_id?: string | null;
            /** Team */
            team?: string | null;
            /** Time S */
            time_s: number;
            /** Xg */
            xg?: number | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /** Engine Version */
            engine_version: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** MetaResponse */
        MetaResponse: {
            /** Api Version */
            api_version: string;
            /** Engine Version */
            engine_version: string;
            /** Environment */
            environment: string;
        };
        /** MonteCarloRequest */
        MonteCarloRequest: {
            /**
             * Attacking Team Id
             * @default england
             */
            attacking_team_id?: string;
            /**
             * Defending Team Id
             * @default argentina
             */
            defending_team_id?: string;
            /**
             * N Sims
             * @default 200
             */
            n_sims?: number;
            /**
             * Root Seed
             * @default 0
             */
            root_seed?: number;
            /** Routine Id */
            routine_id: string;
            /** Scheme Id */
            scheme_id: string;
        };
        /** MonteCarloResponse */
        MonteCarloResponse: {
            /** Engine Version */
            engine_version: string;
            /** Mean Xg */
            mean_xg: number;
            /** N Sims */
            n_sims: number;
            /** N Xg Scored */
            n_xg_scored: number;
            /** Outcome Counts */
            outcome_counts: {
                [key: string]: number;
            };
            p_clearance: components["schemas"]["ProportionCIDTO"];
            p_first_contact_attack: components["schemas"]["ProportionCIDTO"];
            p_goal: components["schemas"]["ProportionCIDTO"];
            p_header_shot: components["schemas"]["ProportionCIDTO"];
            p_possession_recovered: components["schemas"]["ProportionCIDTO"];
            p_shot: components["schemas"]["ProportionCIDTO"];
            /** Root Seed */
            root_seed: number;
            /** Xg Model */
            xg_model?: string | null;
        };
        /** PlayerDTO */
        PlayerDTO: {
            /** Delivery */
            delivery: number;
            /** Display Name */
            display_name: string;
            /** Heading */
            heading: number;
            /** Height M */
            height_m: number;
            /** Jump Reach M */
            jump_reach_m: number;
            /** Player Id */
            player_id: string;
            /** Position Group */
            position_group: string;
            /** Source */
            source: string;
        };
        /**
         * ProblemDetail
         * @description RFC 9457 problem-details body — the API's single error contract.
         */
        ProblemDetail: {
            /** Detail */
            detail: string;
            /** Errors */
            errors?: components["schemas"]["ProblemFieldError"][] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** ProblemFieldError */
        ProblemFieldError: {
            /** Loc */
            loc: (string | number)[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        };
        /** ProportionCIDTO */
        ProportionCIDTO: {
            /** Hi */
            hi: number;
            /** K */
            k: number;
            /** Lo */
            lo: number;
            /** N */
            n: number;
            /** P */
            p: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Checks */
            checks: {
                [key: string]: "ok" | "skipped";
            };
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
        /** RoutineSummary */
        RoutineSummary: {
            /** Name */
            name: string;
            /** Routine Id */
            routine_id: string;
            /** Set Piece */
            set_piece: string;
        };
        /** ScenarioCreate */
        ScenarioCreate: {
            /**
             * Attacking Team Id
             * @default england
             */
            attacking_team_id?: string;
            /**
             * Defending Team Id
             * @default argentina
             */
            defending_team_id?: string;
            /** Name */
            name: string;
            /** Routine Id */
            routine_id: string;
            /** Scheme Id */
            scheme_id: string;
        };
        /** ScenarioDTO */
        ScenarioDTO: {
            /** Created At */
            created_at: string;
            /** Name */
            name: string;
            /** Scenario Hash */
            scenario_hash: string;
            /** Scenario Id */
            scenario_id: string;
            /** Spec */
            spec: {
                [key: string]: string;
            };
        };
        /** SchemeSummary */
        SchemeSummary: {
            /** Name */
            name: string;
            /** Scheme Id */
            scheme_id: string;
        };
        /** SimRunCreate */
        SimRunCreate: {
            /**
             * N Sims
             * @default 1000
             */
            n_sims?: number;
            /**
             * Root Seed
             * @default 0
             */
            root_seed?: number;
            /** Scenario Id */
            scenario_id: string;
        };
        /** SimRunResultDTO */
        SimRunResultDTO: {
            /** Engine Version */
            engine_version: string;
            /** Mean Xg */
            mean_xg: number;
            /** N Sims */
            n_sims: number;
            /** N Xg Scored */
            n_xg_scored: number;
            /** Outcome Counts */
            outcome_counts: {
                [key: string]: number;
            };
            p_clearance: components["schemas"]["ProportionCIDTO"];
            p_first_contact_attack: components["schemas"]["ProportionCIDTO"];
            p_goal: components["schemas"]["ProportionCIDTO"];
            p_header_shot: components["schemas"]["ProportionCIDTO"];
            p_possession_recovered: components["schemas"]["ProportionCIDTO"];
            p_shot: components["schemas"]["ProportionCIDTO"];
            /** Replay Seeds */
            replay_seeds: {
                [key: string]: number;
            };
            /** Root Seed */
            root_seed: number;
            /** Xg Model */
            xg_model?: string | null;
            /** Xg Samples */
            xg_samples: number[];
        };
        /** SimRunStatusDTO */
        SimRunStatusDTO: {
            /** Created At */
            created_at: string;
            /** Engine Version */
            engine_version: string;
            /** Error */
            error?: {
                [key: string]: string;
            } | null;
            /** N Sims */
            n_sims: number;
            /** Progress */
            progress: number;
            result?: components["schemas"]["SimRunResultDTO"] | null;
            /** Root Seed */
            root_seed: number;
            /** Run Id */
            run_id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "complete" | "failed";
        };
        /** SimulateRequest */
        SimulateRequest: {
            /**
             * Attacking Team Id
             * @default england
             */
            attacking_team_id?: string;
            /**
             * Defending Team Id
             * @default argentina
             */
            defending_team_id?: string;
            /** Routine Id */
            routine_id: string;
            /** Scheme Id */
            scheme_id: string;
            /**
             * Seed
             * @default 0
             */
            seed?: number;
        };
        /** SimulateResponse */
        SimulateResponse: {
            /** Att Tracks */
            att_tracks: number[][][];
            /** Ball Path */
            ball_path: number[][];
            /** Def Tracks */
            def_tracks: number[][][];
            /** Engine Version */
            engine_version: string;
            /** Events */
            events: components["schemas"]["EventDTO"][];
            /** Outcome */
            outcome: string;
            /** Seed */
            seed: number;
            /** Track Times S */
            track_times_s: number[];
        };
        /** TeamSummaryDTO */
        TeamSummaryDTO: {
            /** Country */
            country: string;
            /** N Players */
            n_players: number;
            /** Name */
            name: string;
            /** Team Id */
            team_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    players_api_v1_players_get: {
        parameters: {
            query: {
                team: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDTO"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDTO"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_scenario_api_v1_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDTO"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_scenario_api_v1_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDTO"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    montecarlo_api_v1_setpieces_montecarlo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonteCarloResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_routines_api_v1_setpieces_routines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSummary"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_schemes_api_v1_setpieces_schemes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemeSummary"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    simulate_api_v1_setpieces_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_sim_run_api_v1_sim_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimRunStatusDTO"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_sim_run_api_v1_sim_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimRunStatusDTO"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    sim_run_events_api_v1_sim_runs__run_id__events_get: {
        parameters: {
            query?: {
                sample?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_teams_api_v1_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSummaryDTO"][];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
